### ISSUE TITLE
Continue/maintaining django-background-task

### ISSUE THREAD

**Issue by philippeowagner** [lilspikey/django-background-task#13]
Hi @lilspikey 

Based on #12, It seems that you stopped maintaining this project. Is this right? 
If so, we https://github.com/arteria, would like to continue django-background-task. We use this app in production in various project and we would also invest in it by adding more useful feature, for example #6. 

What do you think about that?

**Comment by lilspikey** [comment]
Hi Philippe,

I've not deliberately stopped maintaining this.  Real life has just got in
the way.  Issue #12 arrived after my daughter (2nd child) was only a few
weeks old.  I've been playing catchup with sleep and work ever since.

Hopefully I'll get some time and motivation to pick things back up, but as
issue #12 and #6 haven't been relevant to my work needs I've not got around
to doing them.

Obviously the beauty of github means you could fork this project if you
need to, but I do intend to maintain this going forward.

cheers,

John


On 4 March 2015 at 19:51, Philippe O. Wagner <notifications@github.com>
wrote:

> Hi @lilspikey <https://github.com/lilspikey>
>
> Based on #12 <https://github.com/lilspikey/django-background-task/pull/12>,
> It seems that you stopped maintaining this project. Is this right?
> If so, we https://github.com/arteria, would like to continue
> django-background-task. We use this app in production in various project
> and we would also invest in it by adding more useful feature, for example
> #6 <https://github.com/lilspikey/django-background-task/issues/6>.
>
> What do you think about that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lilspikey/django-background-task/issues/13>.
>



-- 
http://psychicorigami.com/

**Comment by philippeowagner** [comment]
Too many forks let the project dilute. Many great features are distributed over forks. 
They should be combined again and an up-to-date release should then be placed on PyPI to allow others to use this great app in production. 

Together we are stronger: what do you @lilspikey  think about creating an Github organisation (you could still be the owner!) and you will grant commit right to the arteria team. We chould handle the releasing and maintenance stuff. [Here a reference](https://github.com/arteria/django-hijack) of one of our own open sourced projects. 

We could then continue the development and evolve django-background-task together.

**Comment by lilspikey** [comment]
Right so I see you have forked this.  I had kind of hoped that you'd have just submitted a pull request or something.

Still I guess that's the way things go.  Good luck.
